config/routes.rb
Rails.application.routes.draw do
root 'home#top'
get 'home/abaut'


devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  get 'home/mypage' => "books#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :books
	resources :users

resources :users, only: [:show, :edit]
 end

app/models/book.rb
class Book < ApplicationRecord
	validates :title,presence: true
	validates :body,presence: true
	validates :body,length: { maximum: 200 } 
	belongs_to :user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
	def new
  	@book = Book.new
  end

  def create
        # ストロングパラメーターを使用
         @book = Book.new(book_params)
         @book.user_id = current_user.id
        # DBへ保存する
        if @book.save
        # トップ画面へリダイレクト
          redirect_to book_path(@book)
        else
          @books = Book.all
         render 'index'
        end
  end

  def index
  	@books = Book.all
  	@book = Book.new

  end
  
  def show
    @books = Book.find(params[:id])
    @book = Book.new
      @users = User.all
	end

  def edit
	    @book = Book.find(params[:id])
      if @book.user == current_user
      else
        redirect_to book_path(@book)
      end
	end

	def update
	    book = Book.find(params[:id])
	    if 
	    book.update(book_params)
	    redirect_to books_path
	    flash[:notice] = "Book was successfully update."
    	end
  end

  def home
      @books = current_user.books  # ここを記述
      @book = Book.new
  end

	def destroy
    book = Book.find(params[:id])
    if
      book.destroy
      redirect_to books_path
      flash[:notice] = "Book was successfully destroyed."
    end
  end

private
	    def book_params
	        params.require(:book).permit(:title, :body)
	    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="container"> <!-- ここを追加 -->
      <div class="row">
             <div class="col-xs-12">
<h1>編集画面</h1>
<%= form_for(@book) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <input type="submit" name="commit" value="保存" data-disable-with="保存" class="btn btn-primary btn-lg active">
                
    <% end %>

<button type="button" class="btn btn-primary btn-lg active"><%= link_to "戻る", books_path %></button>
</div>
</div>
</div>

app/views/books/home.html.erb
<div class="container"> <!-- ここを追加 -->
      <div class="row">
             <div class="col-xs-4">

            <div><h1>ユーザー</h1>
<h2><%= current_user.name %></h2>
<h2>Introduction<br><%= current_user.introduction %></h2>
<button type="button" class="btn btn-primary btn-lg active"><%= link_to 'ユーザー編集', edit_user_path(current_user.id),class: "btncolor"%></button><br>
<%= attachment_image_tag current_user, :image, :fill, 100, 100,
fallback:'no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6', format: 'jpeg', class: "img-circle profile-img" %></div>
        
        





        
<div><h1>新規投稿</h1>
<!-- form_for部分 -->


             <%= form_for(@book) do |f| %>
                <h4>タイトル</h4>
                <%= f.text_field :title %>
                <h4>本文</h4>
                <%= f.text_area :body %>
                <input type="submit" name="commit" value="投稿" data-disable-with="投稿" class="btn btn-primary btn-lg active">
            <% end %></div>
</div>

<div class="col-xs-8"> 
            <div>
            <h1>投稿一覧</h1>
            <table class="table">
                <thead>
                <tr>
                    <td>image</td>
                    <td>タイトル</td>
                    <td>本文</td>
                    <td></td>
                    <td></td>
                </tr>
            </thead>
                <% @books.each do |book| %>
                <tbody>
                    <tr>
                        <td><%= attachment_image_tag book.user, :image,  fallback:'no_image.jpg',format: 'jpeg', class: "img-circle pull-left profile-img",size: '100x100' %></td>
                        <td><%= book.title %></td>
                        <td><%= book.body %></td>
                        <td><button type="button" class="btn btn-primary btn-lg active"><%=link_to '編集', edit_book_path(book.id) ,class: "btncolor"%></button></td>
                        <td><button type="button" class="btn btn-primary btn-lg active"><%=link_to '表示', book_path(book.id),class: "btncolor" %></button></td>
                        <td><button type="button" class="btn btn-primary btn-lg active"><%=link_to "削除", book_path(book.id),class: "btncolor", method: :delete, "data-confirm" => "本当に削除しますか？" %></button></td>
                    </tr>
                </tbody>
                <% end %>
            </table>
            </div>
            </div>
            </div>
            </div>

app/views/books/index.html.erb
<div class="container"> <!-- ここを追加 -->
      <div class="row">
             <div class="col-xs-4">

            <div><h1>ユーザー</h1>
<h2><%= current_user.name %></h2>
<h2>Introduction<br><%= current_user.introduction %></h2>
<button type="button" class="btn btn-primary btn-lg active"><%= link_to 'ユーザー編集', edit_user_path(current_user.id),class: "btncolor"%></button><br>
<%= attachment_image_tag current_user, :image, :fill, 100, 100, fallback:'no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6', format: 'jpeg', class: "img-circle profile-img" %></div>

<div><h1>新規投稿</h1>
<!-- form_for部分 -->


             <%= form_for(@book) do |f| %>

              <% if @book.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
                <ul>
                  <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <h4>タイトル</h4>
                <%= f.text_field :title %>
                <h4>本文</h4>
                <%= f.text_area :body %>
                <input type="submit" name="commit" value="投稿" data-disable-with="投稿" class="btn btn-primary btn-lg active">
                
            <% end %></div>
</div>
<div class="col-xs-8"> 
            <div>
             <h1>投稿一覧</h1>
            <table class="table">
                <thead>
                <tr>
                    <td>タイトル</td>
                    <td>本分</td>
                    <td></td>
                    <td></td>
                </tr>
            </thead>
                <% @books.each do |book| %>
                <tbody>
                    <tr>
                        <td><%= attachment_image_tag book.user, :image,  fallback:'no_image.jpg',format: 'jpeg', class: "img-circle pull-left profile-img",size: '100x100' %></td>
                        <td><%= book.title %></td>
                        <td><%= book.body %></td>
                        
                        <td><button type="button" class="btn btn-primary btn-lg active"><%=link_to '表示', book_path(book.id),class: "btncolor" %></button></td>
                        
                    </tr>
                </tbody>
                <% end %>
               </table>
              </div>
            </div>
           </div>
          </div>

app/views/books/new.html.erb
<div class="container"> <!-- ここを追加 -->
      <div class="row">
             <div class="col-xs-12">
<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(@book) do |f| %>
 
    <h4>タイトル</h4>
    <%= f.text_field :title %>
 
    <h4>本文</h4>
    <%= f.text_area :body %>
 
                <input type="submit" name="commit" value="投稿" data-disable-with="投稿" class="btn btn-primary btn-lg active">
    
 
<% end %>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container"> <!-- ここを追加 -->
      <div class="row">
             <div class="col-xs-4">

            <div><h1>ユーザー</h1>
<h2><%= @books.user.name %></h2>
<h2>Introduction<br><%= @books.user.introduction %></h2>
<button type="button" class="btn btn-primary btn-lg active"><%= link_to 'ユーザー編集', edit_user_path(current_user.id),class: "btncolor"%></button><br>
<%= attachment_image_tag @books.user, :image, :fill, 100, 100,fallback:'no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6', format: 'jpeg', class: "img-circle profile-img" %></div>
        
        





        <div><h1>新規投稿</h1>
<!-- form_for部分 -->


             <%= form_for(@book) do |f| %>
                <h4>タイトル</h4>
                <%= f.text_field :title %>
                <h4>本文</h4>
                <%= f.text_area :body %>
                <input type="submit" name="commit" value="投稿" data-disable-with="投稿" class="btn btn-primary btn-lg active">
                
            <% end %></div>
</div>



<%= flash[:notice]%>
<div class="col-xs-8"> 
	<h2>Book detail</h2>

          <table class="table">
            <thead>
            <tbody>
                <tr>
                  <td><h2><%= @books.user.name %></h2></td>
                  <td><%= attachment_image_tag @books.user, :image,  fallback:'no_image.jpg',format: 'jpeg', class: "img-circle pull-left profile-img",size: '100x100' %></td>
                  <td><h1>タイトル</h1></td>
                  <td><h2><%= @books.title %></h2></td>
                  <td><h1>本文</h1></td>
                  <td><h2><%= @books.body %></h2></td>
                </tr>
          </thead>
          </tbody>
        </table>
        <ul>


                  <li><button type="button" class="btn btn-primary btn-lg active"><%= link_to "戻る", books_path,class: "btncolor" %></button></li>
                  <% if @books.user == current_user %></li>
                  <li><button type="button" class="btn btn-primary btn-lg active"><%= link_to "編集", edit_book_path(@books.id),class: "btncolor" %></button></li>
                  <% end %>
                  <% if @books.user == current_user %>
                  <li>
                    <button type="button" class="btn btn-primary btn-lg active"><%= link_to "削除", book_path(@books.id),class: "btncolor", method: :delete ,"data-confirm" => "本当に削除しますか？" %></button>
                  </li>
              <% end %>
          </ul>
        </div>
      </div>
    </div>